### ISSUE TITLE
Bug: error in unit tests on Models.py, class Cocktail

### ISSUE THREAD

**Issue by seshutter** [crakkerjak/cs373-idb#32]
Need to import db in models.py in order for unit tests to pass

Error:
Traceback (most recent call last):
  File "tests.py", line 10, in <module>
    from models import Cocktail, Ingredient
  File "/Users/seshutter/Documents/Spring 2016/CS 373 Software Engineering/Project 3/cs373-idb/models.py", line 7, in <module>
    class Cocktail(Base):
  File "/Users/seshutter/Documents/Spring 2016/CS 373 Software Engineering/Project 3/cs373-idb/models.py", line 12, in Cocktail
    ingredients = db.relationship('Ingredient', backref='cocktail',
NameError: name 'db' is not defined
make: **\* [test] Error 1

**Comment by ctimaeus** [comment]
Added:

from flask_sqlalchemy import sqlalchemy
db = SQLAlchemy()
